baseURL = 'https://gr.ht/'
languageCode = 'en-us'
title = 'The Gray Hatter'
uglyurls = true
enableRobotsTXT = true
#summaryLength = 20
[params]
	email = 'grht@gr.ht'
	Author = 'Gray Hatter'

[permalinks]
	posts = '/:year/:month/:day/:slug'
	'/' = '/:filename'


[markup.goldmark.renderer]
unsafe = true


[taxonomies]
tag = "tags"
author = "author"
